GET {{URL}}/hotel
###
GET {{URL}}/hotel/1
###
POST {{URL}}/hotel/
Content-Type: application/json

{
  "name": "California",
  "address": "101"
}

###

PUT {{URL}}/hotel/4
Content-Type: application/json

{
"name": "Hotel renamedHotel2",
"address": "Address 1"
}


